aeternity/tipping-community-backend

- logic/profileLogic.js
- test/profile.js
fixes https://github.com/aeternity/superhero-ui/issues/651
> profile now returns firefox parsable date

- logic/backupLogic.js
- logic/pinLogic.js
- logic/profileLogic.js
- migrations/20200630-12-change-ipfs-enum.js
- migrations/20200630-13-add-pins.js
- migrations/_current.json
- models/blacklist.js
- models/enums/blacklist.js
- models/enums/ipfs.js
- models/enums/pin.js
- models/ipfs.js
- models/pin.js
- routes/pinRoutes.js
- server.js
- test/pin.js
- test/profile.js
- utils/auth.js
closes #140 
new endpoints:
`POST /pin/ak_.......` with payload: `{ entryId: 1, type: "TIP" }` --> returns entry with id
`DELETE /pin/1` with payload: `{ author: "ak_..." }` up for discussion @stanislav-slavov @mradkov @thepiwo we could also go with `DELETE /pin/ak_....` with payload `{ entryId: 1, type: "TIP" }`
`GET /pin/ak_...` --> currently only returns the IDs of the pinned items. is this enough? @stanislav-slavov
> enums & pinning endpoints

- logic/cacheLogic.js
- logic/notificationLogic.js
- logic/retipLogic.js
- logic/tipLogic.js
- test/notification.js
- test/re-tip.js
- to be merged after #153 & migration is complete
- enables the notification creation
> enables claim notification creation

- utils/cache.js
> lock keephot without timeout

- logic/linkPreviewLogic.js
> prefixes urls with no protocol for link preview

- utils/aeternity.js
> fix broken event fields

- logic/commentLogic.js
- logic/notificationLogic.js
- migrations/20200921-3-adds-notification-sender.js
- migrations/_current.json
- models/notification.js
- test/notification.js
> adds sender to notifications

- utils/aeternity.js
> abort if zero claim

- logic/cacheLogic.js
- test/aeternity.js
> fix cache for ft account balances

- logic/consentLogic.js
- migrations/20201020-5-add-consent.js
- migrations/_current.json
- models/consent.js
- models/enums/consent.js
- routes/consentRoutes.js
- server.js
- test/consent.js
- utils/auth.js
- utils/testingUtil.js
Adds consent endpoints for rich content previews
> creates basic consent framework

- .github/workflows/nodejs.yml
- package.json
changes:
- includes swagger lint in package json
> feat(swagger): includes swagger lint in package json

- .swaggerDef.js
> fix(swagger): swagger now runs against testnet server

- modules/notification/routes/notificationRoutes.js
> fix(notifications): updates urls in docs (solves #227)

- modules/notification/logic/notificationLogic.js
fixes https://github.com/aeternity/superhero-wallet/issues/701
> fix(notifications): removes future self-notifications

- .mocharc.js
- modules/aeternity/logic/aeternity.js
- modules/aeternity/tests/middleware.js
- modules/cache/logic/cacheLogic.js
- modules/cache/routes/cacheRoutes.js
- modules/cache/tests/cache.js
- modules/notification/logic/notificationLogic.js
- modules/notification/routes/notificationRoutes.js
- modules/token/logic/tokenCacheLogic.js
- modules/token/routes/tokenCacheRoutes.js
- modules/token/tests/tokenCache.js
- package.json
- wordbazaar internals + endpoints
- wrong url in docs for notifications #227 
- removes self notifications #230
> Release v1.5 (#minor)

- modules/cache/logic/cacheLogic.js
- package.json
- removes undefined function from keephot
> Release 1.6.1

- package.json
enforces conventional commit messages
> chore(ci): adds pre-commit verification

- modules/aeternity/logic/mdwLogic.js
- modules/cache/logic/cacheAggregatorLogic.js
- modules/comment/logic/commentLogic.js
- modules/comment/routes/commentRoutes.js
- modules/comment/tests/comments.js
affected areas:
- mdw
- aggregator
- comments
> refactor: class to module

- modules/cache/tests/cache.js
- modules/token/tests/tokenCache.js
- increases timeout as registry gets bigger
- renames cache tests for clarity
> fix(tests): minor fixes

- .eslintrc.js
- bin/www.js
- modules/aeternity/logic/aeternity.js
- modules/aeternity/tests/aeternity.js
- modules/blacklist/logic/blacklistLogic.js
- modules/blacklist/routes/blacklistRoutes.js
- modules/blacklist/tests/blacklist.js
- modules/cache/logic/cacheLogic.js
- modules/cache/tests/cache.js
- modules/cache/utils/cache.js
- modules/comment/tests/comments.js
- modules/domains/tests/static.js
- modules/pin/tests/pin.js
- modules/tip/logic/tipLogic.js
- modules/tip/routes/tipRoutes.js
- modules/tip/tests/re-tip.js
- modules/tip/tests/tips.json
- utils/basicTippingContractUtil.js
still not all broken tests are fixed
> tests: fixes some broken tests + minor refactorings
